# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v

# The lines added by compinstall
zstyle :compinstall filename "${HOME}/.zshrc"

autoload -Uz compinit
compinit

# Lines for antigen setup
if [[ $(uname -s) == "Darwin" ]]
then
    source $(brew --prefix)/share/antigen/antigen.zsh
else
    source /usr/share/zsh/share/antigen.zsh
fi

antigen use oh-my-zsh
antigen theme robbyrussell
antigen apply

# Set GPG TTY
if [[ $(uname -s) == "Linux" ]]
then
    export GPG_TTY=$(tty)
    # Refresh gpg-agent tty in case user switches into an X session
    gpg-connect-agent updatestartuptty /bye >/dev/null

    if grep -c "arch" /etc/os-release > /dev/null 2>&1; then
        # Start the gpg-agent if not already running
        if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
            gpg-connect-agent /bye >/dev/null 2>&1
        fi

        # Set SSH to use gpg-agent
        unset SSH_AGENT_PID
        if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
            export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
        fi
    fi

    if grep -c "ubuntu" /etc/os-release > /dev/null 2>&1; then
        # Start the gpg-agent if not already running
        if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
            gpg-agent --daemon --enable-ssh-support
        fi

        # Set SSH to use gpg-agent
        unset SSH_AGENT_PID
        if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
            export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
        fi
    fi
fi
