# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/jiangchao/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines for antigen setup
source $(brew --prefix)/share/antigen/antigen.zsh
  
antigen use oh-my-zsh
antigen theme robbyrussell
antigen apply
# End of lines for antigen setup
     
